(define (square size)
  (define half-size (/ size 2))
  (tortoise-penup)
  (tortoise-move (* -1 half-size))
  (tortoise-turn 90)
  (tortoise-turn (* -1 half-size))
  (tortoise-pendown)
  (tortoise-move size)
  (tortoise-turn 90)
  (tortoise-move size)
  (tortoise-turn 90)
  (tortoise-move size)
  (tortoise-turn 90)
  (tortoise-move size)
  (tortoise-turn 90))

(square 5)
(square 7)
(square 9)
(square 11)
  
