										; utils
(define size 10)
(define (square x)
  (* x x))
(define hyp
  (sqrt (+ (square size) (square size))))
										; center horizontal
(tortoise-center)
(tortoise-penup)
(tortoise-move -10)
(tortoise-pendown)
(tortoise-move 20)
										; center vertical
(tortoise-center)
(tortoise-penup)
(tortoise-turn 90)
(tortoise-move 10)
(tortoise-pendown)
(tortoise-turn 180)
(tortoise-move 20)
										; diagonal 1
(tortoise-center)
(tortoise-penup)
(tortoise-turn 135)
(tortoise-move hyp)
(tortoise-pendown)
(tortoise-turn 180)
(tortoise-move (* 2 hyp))
										; diagonal 2
(tortoise-center)
(tortoise-penup)
(tortoise-turn 45)
(tortoise-move hyp)
(tortoise-pendown)
(tortoise-turn 180)
(tortoise-move (* 2 hyp))
										; square
(tortoise-center)
(tortoise-penup)
(tortoise-move -5)
(tortoise-turn 270)
(tortoise-move -5)
(tortoise-pendown)
(tortoise-move 10)
(tortoise-turn 90)
(tortoise-move 10)
(tortoise-turn 90)
(tortoise-move 10)
(tortoise-turn 90)
(tortoise-move 10)
										; circle
(define (circle)
  (define (iter a)
	(tortoise-center)
	(tortoise-turn a)
	(tortoise-penup)
	(tortoise-move 5)
	(tortoise-turn 90)
	(tortoise-pendown)
	(tortoise-move 0.1)
	(if (= a 360)
		0
		(iter (+ a 1))))
  (iter 0))
(circle)

		
